/**
 * Colour themes for the sector pages. Tailwind only generates classes it can
 * see written out in full, so every class below is spelled out literally.
 */
export const THEMES = {
  blue: {
    heroBg: "bg-blue-950",
    outline: "focus-visible:outline-blue-300",
    outlineDark: "focus-visible:outline-blue-400",
    outlineLight: "focus-visible:outline-blue-600",
    btn: "bg-blue-500 text-slate-950 hover:bg-blue-400",
    iconBox: "bg-blue-100 text-blue-700",
    check: "text-blue-600",
    checkDark: "text-blue-400",
    step: "bg-blue-600",
    featuredRing: "ring-blue-500",
    featuredBadge: "bg-blue-500 text-slate-950",
    chip: "bg-blue-50 text-blue-700",
    chipDark: "bg-blue-500/15 text-blue-300",
    liveBadge: "bg-blue-500/15 text-blue-300",
    ping: "bg-blue-400",
    keep: "text-blue-400",
  },
  orange: {
    heroBg: "bg-orange-950",
    outline: "focus-visible:outline-orange-300",
    outlineDark: "focus-visible:outline-orange-400",
    outlineLight: "focus-visible:outline-orange-600",
    btn: "bg-orange-500 text-slate-950 hover:bg-orange-400",
    iconBox: "bg-orange-100 text-orange-700",
    check: "text-orange-600",
    checkDark: "text-orange-400",
    step: "bg-orange-600",
    featuredRing: "ring-orange-500",
    featuredBadge: "bg-orange-500 text-slate-950",
    chip: "bg-orange-50 text-orange-700",
    chipDark: "bg-orange-500/15 text-orange-300",
    liveBadge: "bg-orange-500/15 text-orange-300",
    ping: "bg-orange-400",
    keep: "text-orange-400",
  },
  violet: {
    heroBg: "bg-violet-950",
    outline: "focus-visible:outline-violet-300",
    outlineDark: "focus-visible:outline-violet-400",
    outlineLight: "focus-visible:outline-violet-600",
    btn: "bg-violet-500 text-slate-950 hover:bg-violet-400",
    iconBox: "bg-violet-100 text-violet-700",
    check: "text-violet-600",
    checkDark: "text-violet-400",
    step: "bg-violet-600",
    featuredRing: "ring-violet-500",
    featuredBadge: "bg-violet-500 text-slate-950",
    chip: "bg-violet-50 text-violet-700",
    chipDark: "bg-violet-500/15 text-violet-300",
    liveBadge: "bg-violet-500/15 text-violet-300",
    ping: "bg-violet-400",
    keep: "text-violet-400",
  },
  rose: {
    heroBg: "bg-rose-950",
    outline: "focus-visible:outline-rose-300",
    outlineDark: "focus-visible:outline-rose-400",
    outlineLight: "focus-visible:outline-rose-600",
    btn: "bg-rose-500 text-slate-950 hover:bg-rose-400",
    iconBox: "bg-rose-100 text-rose-700",
    check: "text-rose-600",
    checkDark: "text-rose-400",
    step: "bg-rose-600",
    featuredRing: "ring-rose-500",
    featuredBadge: "bg-rose-500 text-slate-950",
    chip: "bg-rose-50 text-rose-700",
    chipDark: "bg-rose-500/15 text-rose-300",
    liveBadge: "bg-rose-500/15 text-rose-300",
    ping: "bg-rose-400",
    keep: "text-rose-400",
  },
} as const;

export type ThemeKey = keyof typeof THEMES;
